name: physio_track
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  google_fonts: ^4.0.4
  http: ^0.13.5
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  google_sign_in: ^6.1.0
  cupertino_icons: ^1.0.5
  cloud_firestore: ^4.8.0
  persistent_bottom_nav_bar: ^5.0.2
  # intl: ^0.18.1
  intl: ^0.17.0
  image_picker: ^0.8.7+5
  firebase_storage: ^11.2.2
  flutter_native_splash: ^2.2.19
  flutter_lottie: ^0.2.0
  material_design_icons_flutter: ^7.0.7296
  webview_flutter: ^4.2.4
  youtube_player_iframe: ^4.0.4
  flutter_inappwebview: ^5.7.2+3
  url_launcher: ^6.1.11
  youtube_player_flutter: ^8.0.0
  youtube_explode_dart: ^1.12.4
  background_fetch: '^1.2.1'
  #flutter_local_notifications: ^15.1.0+1
  #flutter_local_notifications: ^6.1.0
  flutter_local_notifications: ^16.2.0
  firebase_messaging: ^14.6.6
  app_settings: ^5.0.0
  provider: ^5.0.0
  # shared_preferences: ^2.0.10
  percent_indicator: ^4.2.3
  workmanager: ^0.5.0
  confetti: ^0.7.0
  # flutter_youtube_view: ^2.0.4
  fl_chart: ^0.62.0
  carousel_slider: ^4.2.1
  googleapis: ^11.3.0
  googleapis_auth: ^1.4.1
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  flutter_datetime_picker: ^1.5.1
  date_picker_timeline: ^1.2.3
  font_awesome_flutter: ^10.4.0
  table_calendar: ^3.0.8
  auto_size_text: ^3.0.0
  flutter_dotenv: ^5.1.0
  avatar_glow: ^2.0.2
  easy_localization: ^3.0.3
  shimmer: ^2.0.0
  rxdart: ^0.27.1
  flutter_native_timezone: ^1.1.0
  flutter_timezone: ^1.0.8
  flutter_email_sender: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - .env